### ISSUE TITLE
https://github.com/aliabbani/javaScript-capstone-project/projects

### ISSUE THREAD

**Issue by aliabbani** [aliabbani/Lemonade-api#21]
We are a team divided between 2 partners: 
Student A: Ali Abbani,
Student B: Elmar Abdulkarimov

**Comment by DeliceLydia** [comment]
# Status: Change Requested

Hello Team,

your Kanban board looks good already but you need to fix few things to be able to
move on to the next project
- [x] Cards should be assigned to the team members you should see a circle with user's avatar on each card
![g](https://user-images.githubusercontent.com/44745855/132228055-b205bf05-1952-48c4-8b6c-26e8d418ec5f.png)

N.B Remember next time to submit an issue link with GitHub repo link

**Comment by elmar8287** [comment]
Good time @DeliceLydia 👋 ,

Thank you for your review. The issue is fixed and now it looks correct 🥇

**Comment by Dipeshtwis** [comment]
# Status: Approved ✔️

## Hi @elmar8287 &  @aliabbani,

Good job on implementing the suggested changes. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by aliabbani** [comment]
Thank you @Dipeshtwis for your support
